### ISSUE TITLE
Can not find the library

### ISSUE THREAD

**Issue by imdatcandan** [Trendyol/mockingstar-android#2]
`Failed to resolve: com.trendyol.mockingstar:mockingstar:1.0.0
`
Are we sure that dependcy is correct because documentation and read me showing different dependencies, I tried both but none of them worked. Would be great if you can make it clear.
Thanks in advance.

**Comment by yigitozgumus** [comment]
Hello,

It might be best to refer to each repository readme to get the latest information. 

For mockingstar-android, you can download the library using the 

```gradle
implementation("com.github.Trendyol:mockingstar-android:{latest-version}")
```

Also, we keep the current version as a jitpack badge. You can find the full version list through [here](https://jitpack.io/#Trendyol/mockingstar-android).
