### ISSUE TITLE
java.net.SocketTimeoutException: failed to connect to /10.0.2.2 (port 8008) from /192.168.0.104 (port 52898) after 10000ms

### ISSUE THREAD

**Issue by imdatcandan** [Trendyol/mockingstar-android#3]
When I try on my project or your sample one, I have this crash do you have any recommondation to fix it?

**Comment by yusufozgul** [comment]
Hello, can you check MockingStar app is running: https://github.com/Trendyol/mockingstar
![Screenshot 2024-03-11 at 16 20 13](https://github.com/Trendyol/mockingstar-android/assets/26109252/e235ff38-6ef1-48d4-b578-e919abb947d7)
